version: 0.0
os: linux
files:
- source: /app.js
  destination: /home/ec2-user/node-website
  overwrite: yes
- source: /package.json
  destination: /home/ec2-user/node-website
  overwrite: yes
- source: /public/
  destination: /home/ec2-user/node-website/public
  overwrite: yes
- source: /scripts/requirements.txt
  destination: /home/ec2-user/scripts
  overwrite: yes
hooks:
  AfterInstall:
  - location: scripts/install_python3
    timeout: 300
    runas: root
  - location: scripts/codestar_remote_access
    timeout: 300
    runas: root
  - location: scripts/install_node
    timeout: 300
    runas: root
  - location: scripts/install_httpd
    timeout: 300
    runas: root
  ApplicationStart:
  - location: scripts/start_server
    timeout: 300
    runas: root
  ApplicationStop:
  - location: scripts/stop_server
    timeout: 300
    runas: root

