#!/bin/bash

# Install apache
yum -y install httpd-2.4.41

# Set up proxy for Node server
cat <<EOT >> /etc/httpd/conf/httpd.conf
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

ProxyRequests Off
ProxyPass / http://localhost:3000/
ProxyPassReverse / http://localhost:3000/

<Location "/">
  Order allow,deny
  Allow from all
</Location>
EOT

#For Troubleshooting of Deployment
#CodeAgent Log: less /var/log/aws/codedeploy-agent/codedeploy-agent.log
#Script log: tail -5 /opt/codedeploy-agent/deployment-root/b05763f4-df88-43e7-979a-fdf6db50872d/d-CRMEG7EO5/logs/scripts.log
